name: build-pipeline
on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Checkout
        uses: actions/checkout@v2

      - name: gofmt check
        run: |
          if [ "$(gofmt -s -l . | wc -l)" -ne 0 ]
          then
           echo "The following files were found to be not go formatted:"
           gofmt -s -l .
           exit 1
          fi

      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v1

      - name: Run Unit Tests
        run: go test -v ./...

      - name: unused-package check
        run: make unused-package-check

      - name: Build Binaries
        run: make build
